# TODO: Implement behat and unit testing
# TODO: Once tests are implemented, test on 5.3 and 5.4 versions too

language: php

php:
    - 5.5

env:
    global:
        - SYMFONY_ENV=test

before_install:
    - composer self-update
    - npm install -g grunt-cli bower
    - gem install compass

install:
    - composer install --prefer-source
    - npm install
    - bower install

script:
    - grunt default
