[{capture append="oxidBlock_pageBody"}]
    [{include file="layout/offcanvas.tpl" id="myNavmenu"}]
    [{include file="layout/header.tpl" offcanvasId="myNavmenu"}]
    <div class="container">
        [{foreach from=$oxidBlock_content item="_block"}]
            [{$_block}]
        [{/foreach}]
    </div>
    [{include file="layout/footer.tpl"}]
    [{if $oView->getClassName() != "details"}]
        [{insert name="oxid_tracker" title=$oView->getTitle()}]
    [{/if}]
[{/capture}]
[{capture append="oxidBlock_pagePopup"}]
    [{include file="widget/header/loginbox.tpl"}]
[{/capture}]
[{include file="layout/base.tpl"}]
